pipeline {
  agent any
  stages {
    stage('Build Web') {
      steps {
        echo "Web is ready on: ${webSiteUrl}"
      }
    }
    stage('Build Test') {
      steps {
        echo "WORKSPACE is: ${WORKSPACE}"
        sh '''cd JenkinsForTesting/juiceShopTestInDocker
          ls -la
          docker build -t autotest_web_container .
          docker images
        '''
      }
    }
    stage('Run Test') {
      failFast true
      steps {
            sh '''cd JenkinsForTesting/juiceShopTestInDocker
              ls -la
              docker run --tty -v $(pwd):/user/test/ -w /user/test/ autotest_web_container python test.py --url ${webSiteUrl}
            '''
      } 
    }
  }
}