pipeline { // определение декларативного pipeline
  agent any // определение, что будет запущено на любом агенте
  stages { // stages которые будем запускать
    stage('Get python3 version') { // первый stage
      steps {
        sh 'python3 --version'
      }
    }
    stage('Start python3 python-hello.py') { // второй stage
      steps {
        sh 'python3 python-hello.py'
      }
    }
  }
}