pipeline {
  agent any
  stages {
    stage('Build Web') {
      steps {
        echo "Web is ready on: ${webSiteUrl}"
      }
    }
    stage('Run Test') {
      failFast true
      steps {
        sh 'python3 JenkinsForTesting/juiceShopTestNotInDocker/test.py --url ${webSiteUrl} --alluredir=allure-result'
      }
    }
  }
}