pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'python3 JenkinsForTesting/juiceShopTestNotInDocker/ops.py'
      }
    }
    stage('Run Test') {
      steps {
        sh 'python3 -m pytest JenkinsForTesting/juiceShopTestNotInDocker/test_ops.py'
      }
    }
    post {
      always {
        script {
          allure([
            includeProperties: false,
            jdk: '',
            properties: [],
            reportBuildPolicy: 'ALWAYS',
            results: [[path: 'allure-results']]
          ])
        }
      }
    }
  }
}