pipeline { // определение декларативного pipeline
  agent any // определение, что будет запущено на любом агенте
  stages { // stages которые будем запускать
    stage('Get python3 version') { // первый stage
      steps {
        echo "WORKSPACE is: ${WORKSPACE}"
		sh '''cd JenkinsForTesting/juiceShopTest
            ls -la
			docker build -t autotest_web_container .
            docker images
            '''
      }
    }
    stage('Start python3 test.py') { // второй stage
      steps {
        echo "WORKSPACE is: ${WORKSPACE}"
        sh '''cd JenkinsForTesting/juiceShopTest
			docker run -i -v $(pwd):/user/test/ -w /user/test/ autotest_web_container python test.py --url ${webSiteUrl}
            '''
      }
    }
  }
}