pipeline { // определение декларативного pipeline
  agent any // определение, что будет запущено на любом агенте
  stages { // stages которые будем запускать
    stage('Get python3 version') { // первый stage
      steps {
        sh '''python3 --version
            apt-get install python3-pip
            pip install --upgrade pip
            pip install pytest && pip install selenium
            '''
      }
    }
    stage('Start python3 test.py') { // второй stage
      steps {
        echo "WORKSPACE is: ${WORKSPACE}"
        sh "python3 JenkinsForTesting/juiceShopTest/test.py --url ${webSiteUrl}"
      }
    }
  }
}